portfolio/urls.py
from django.urls import path
from portfolio.views import *
from . import views

urlpatterns = [
  path('', views.index, name='index'),
  path('portfolio', views.portfolio, name='portfolio_detail'),
  path('search', views.api_call, name='search'),
  path('buy/<str:symbol>', views.buy_stocks, name='buy'),
  path('sell/<str:symbol>', views.sell_stocks, name='sell'),
  path('buy_error', views.buy_error, name='buy_error'),
  path('sell_error', views.sell_error, name='sell_error'),
  path('leaderboard', views.leaderboard, name='leaderboard'),
  path('signup', views.signup, name='signup'),
]

stock_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

portfolio/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User, AbstractUser
from datetime import date

class Stock(models.Model):
  ticker = models.CharField(max_length=5)
  portfolio = models.ForeignKey('Portfolio', on_delete=models.SET_NULL, null=True)
  company = models.CharField(max_length=100)
  price = models.FloatField()
  shares = models.IntegerField()
  stock_cost = models.FloatField()

  def __str__(self):
    return self.ticker

class Portfolio(models.Model):
  investor = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, unique=False)
  portfolio_available_funds = models.FloatField()

  def get_absolute_url(self):
    return reverse("portfolio-detail", kwargs={"pk": self.pk})
  
  def __str__(self):
    return f"{self.investor}'s Portfolio"

templates/base.html
<!DOCTYPE html>
<html lang = 'en'>
<head>
  {% block title %}<title>PORTFOLIO</title>{% endblock %} 
  <meta charset="utf-8">
  <!-- easy viewport optimization -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- bootstrap css -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <!-- loading custom css file -->
  <!--{% load static %}-->
  <!--<link rel="stylesheet" href="{% static 'css/styles.css' %}">-->
</head>
<body class='bg-dark'>
  <nav class='navbar navbar-light bg-light'>
    <div class='container-fluid'>
      <h1 class='navbar-brand'><strong><u>Portfolio Simulator</u></strong></h1>
      <form class='d-flex' method='GET' action='{% url 'search' %}'>
        {% csrf_token %}
        <input class='form-control me-2' type='search' name='ticker_search' onfocus="this.value=''" value='ex.AAPL'>
        <button class='btn btn-outline-dark' type='submit'>Search</button>
      </form>
      <div class='front-header'>
      {% if user.is_authenticated %}
        <p>User: {{ user.get_username }}</p>
        <a class='btn btn-outline-dark' href='{% url 'portfolio_detail' %}'>Your Portfolio</a>
        <a class='btn btn-outline-dark' href='{% url 'leaderboard'%}'>Leaderboard</a>
        <a class='btn btn-outline-dark' href='{% url 'logout' %}'>Logout</a>
      {% else %}  
        <a class='btn btn-outline-dark' href='{% url 'leaderboard'%}'>Leaderboard</a>
        <a class='btn btn-outline-dark' href='{% url 'login'%}'>Login</a>
      {% endif %}
      </div>
    </div>
  </nav>

    <div style='text-align:center; padding-top:20vh; padding-bottom: 20vh; margin-top: 6vh' class='container container-table bg-light rounded'>
    {% block content %}{% endblock %}
    </div>
</body>
</html>

templates/buy_error.html
{% extends 'base.html' %}

{% block content %}
  <p>You do not have enough funds!</p>
{% endblock %}

templates/buy_stocks.html
{% extends 'base.html'%}

{% block content %}
  {% if user.is_authenticated %}
    <h2>Buy</h2>
    <h2>Ticker: {{ symbol }}</h2>
    <h4>${{ price }}</h4>
    <form method='POST' action=''>
      {% csrf_token %}
      {{ form }}
      <button class="btn btn-outline-dark" type='submit'>Buy</button>
    </form>
  {% else %}
    <p>Please login to continue!</p>
  {% endif %}
{% endblock %}

templates/create.html
{% extends 'base.html'%}

{% block content %}
  <h3>Create a New Account</h3>
  <p>Ticker: {{ symbol }}</p>
  <p>Price: {{ price }}</p>
  <form method='POST' action=''>
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Buy</button>
  </form>
{% endblock %}

templates/index.html
{% extends 'base.html'%}

{% block title %} <title>PORTFOLIO</title> {% endblock %}

{% block content %}
<p>Welcome!</p>
<p>Start your portfolio and get trading!</p>
{% endblock %}

templates/leaderboard.html
{% extends 'base.html'%}

{% block content %}
<h2>Leaderboard</h2>
{% for user in page_obj %}
  <p>{{ forloop.counter0|add:page_obj.start_index }}. {{user.investor}}: ${{user.value|floatformat:2}}</p>
{% endfor %}
<br>
<div class='container'>
<div class="pagination" style='justify-content: center;'>
  <span class="step-links">
    {% if page_obj.has_previous %}
      <a href="?page=1">&laquo; first</a>
      <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">next</a>
      <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>
</div>
{% endblock %}

templates/portfolio_detail.html
{% extends 'base.html' %}

{% block content %}
<h2>{{user}}'s Portfolio</h2>
{% if user.portfolio %}
  {% if user.portfolio.stock_set.all %}
  <table style=''>
  <tr>
    <table style='display:inline-block; margin: auto; justify-content:center'>
      <tr>
        <td>Company</td>
        <td>Ticker</td>
        <td>Shares</td>
        <td>Average Price</td>
        <td>Total Cost</td>
      </tr>
      {% for stock in user.portfolio.stock_set.all %}
        <tr>
          <td>{{ stock.company }}</td>
          <td>{{ stock }}</td>
          <td>{{ stock.shares }}</td>
          <td>{{ stock.price|floatformat:2 }}</td>
          <td>{{ stock.stock_cost|floatformat:2 }}</td>
        </tr>
      {% endfor %}
    </table>
    <table style='display:inline-block;'>
      <tr>
        <td>Current Value</td>
      </tr>
      {% for value in current_values %}
      <tr>
        <td>
        {{ value|floatformat:2 }}
        </td>
      </tr>
      {% endfor %}
    </table>
  </tr>
  {% else %}
    <tr>You don't have any stocks!</tr>
  {% endif %}
  <br><tr>Available Funds: ${{ user.portfolio.portfolio_available_funds|floatformat:2 }}</tr><br>
  <tr>Portfolio Value: ${{ portfolio_value|floatformat:2 }}</tr>
  </table>
{% else %}
  <p>You don't have a portfolio!</p>
  <form method='POST' action=''>
  {% csrf_token %}
    {{ form }}
    <button type='submit'>Create</button>
  </form>
{% endif %}
{% endblock %}

templates/search.html
{% extends 'base.html'%}

{% block title %} <title>PORTFOLIO</title> {% endblock %}

{% block content %}
  <h2>{{ companyName }} {% if symbol %} - {% endif %} {{ symbol }}</h2>
  <h4>{{ iexRealtimePrice }}</h4>
  <div>
    {% if symbol %}
    <a class="btn btn-outline-dark" href='{% url 'buy' symbol %}'>BUY</a>
    <a class="btn btn-outline-dark" href='{% url 'sell' symbol %}'>SELL</a>
    {% endif %}
  </div>
{% endblock %}

templates/sell_error.html
{% extends 'base.html' %}

{% block content %}
  <p>Insufficient shares!</p>
{% endblock %}

templates/sell_stocks.html
{% extends 'base.html'%}

{% block content %}
  <h2>Sell</h2>
  {% if current_shares > 0 %}
    <h2>Ticker: {{ symbol }}</h2>
    <h4>${{ price }}</h4>
    <p>Your Shares: {{ current_shares }}</p>
    <form method='POST' action=''>
      {% csrf_token %}
      {{ form }}
      <button class="btn btn-outline-dark" type='submit'>Sell</button>
    </form>
  {% else %}
    <p>You have no shares of this stock to sell!</p>
  {% endif %}
{% endblock %}

templates/signup.html
{% extends 'base.html'%}

{% block content %}
  <h3>Create a New Account</h3>
  <form method='POST' action=''>
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Create</button>
  </form>
{% endblock %}